	.align 2
	@********************** Voicegroup **********************@

	.global voicegroup025
voicegroup025:	@ 0x080EAA74
	voice_square_1_alt 0, 0, 0, 0, 15, 0	@080EAA74
	voice_square_1_alt 0, 1, 0, 0, 15, 0	@080EAA80
	voice_square_1_alt 0, 2, 0, 0, 15, 0	@080EAA8C
	voice_square_1_alt 0, 3, 0, 0, 15, 0	@080EAA98
	voice_square_1_alt 0, 2, 2, 0, 15, 0	@080EAAA4
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAAB0
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAABC
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAAC8
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAAD4
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAAE0
	voice_square_2_alt 0, 0, 0, 15, 0	@080EAAEC
	voice_square_2_alt 1, 0, 0, 15, 0	@080EAAF8
	voice_square_2_alt 2, 0, 0, 15, 0	@080EAB04
	voice_square_2_alt 3, 0, 0, 15, 0	@080EAB10
	voice_square_2_alt 2, 2, 0, 15, 0	@080EAB1C
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB28
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB34
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB40
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB4C
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB58
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB64
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB70
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB7C
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB88
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAB94
	voice_square_1 0, 2, 0, 0, 15, 0	@080EABA0
	voice_square_1 0, 2, 0, 0, 15, 0	@080EABAC
	voice_square_1 0, 2, 0, 0, 15, 0	@080EABB8
	voice_square_1 0, 2, 0, 0, 15, 0	@080EABC4
	voice_square_1 0, 2, 0, 0, 15, 0	@080EABD0
	voice_square_1 0, 2, 0, 0, 15, 0	@080EABDC
	voice_square_1 0, 2, 0, 0, 15, 0	@080EABE8
	voice_square_1 0, 2, 0, 0, 15, 0	@080EABF4
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAC00
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAC0C
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAC18
	voice_square_1_alt 0, 1, 1, 0, 15, 0	@080EAC24
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAC30
	voice_square_2_alt 1, 0, 2, 0, 0	@080EAC3C
	voice_square_2_alt 2, 2, 0, 15, 1	@080EAC48
	voice_programmable_wave_alt ProgrammableWaveData_80EB6EC, 0, 4, 4, 0	@080EAC54
	voice_programmable_wave_alt ProgrammableWaveData_80EB6FC, 0, 0, 15, 0	@080EAC60
	voice_programmable_wave_alt ProgrammableWaveData_80EB70C, 0, 0, 15, 0	@080EAC6C
	voice_programmable_wave_alt ProgrammableWaveData_80EB71C, 0, 0, 15, 0	@080EAC78
	voice_programmable_wave_alt ProgrammableWaveData_80EB72C, 0, 0, 15, 0	@080EAC84
	voice_programmable_wave_alt ProgrammableWaveData_80EB73C, 0, 0, 15, 0	@080EAC90
	voice_programmable_wave_alt ProgrammableWaveData_80EB74C, 0, 0, 15, 0	@080EAC9C
	voice_programmable_wave_alt ProgrammableWaveData_80EB75C, 0, 0, 15, 0	@080EACA8
	voice_programmable_wave_alt ProgrammableWaveData_80EB76C, 0, 3, 0, 2	@080EACB4
	voice_square_1 0, 2, 0, 0, 15, 0	@080EACC0
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@080EACCC
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@080EACD8
	voice_square_2_alt 2, 0, 3, 0, 0	@080EACE4
	voice_programmable_wave_alt ProgrammableWaveData_80EB6EC, 0, 0, 15, 0	@080EACF0
	voice_programmable_wave_alt ProgrammableWaveData_80EB76C, 0, 3, 0, 2	@080EACFC
	voice_programmable_wave_alt ProgrammableWaveData_80EB6EC, 0, 0, 15, 0	@080EAD08
	voice_square_1_alt 0, 0, 0, 0, 15, 5	@080EAD14
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@080EAD20
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@080EAD2C
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@080EAD38
	voice_square_2_alt 0, 0, 4, 0, 0	@080EAD44
	voice_programmable_wave_alt ProgrammableWaveData_80EB76C, 0, 4, 0, 0	@080EAD50
	voice_square_2_alt 0, 0, 4, 4, 0	@080EAD5C
	voice_square_1_alt 0, 1, 0, 3, 0, 0	@080EAD68
	voice_square_1_alt 0, 1, 0, 2, 0, 0	@080EAD74
	voice_square_1_alt 0, 3, 0, 1, 0, 1	@080EAD80
	voice_programmable_wave_alt ProgrammableWaveData_80EB72C, 0, 0, 15, 0	@080EAD8C
	voice_programmable_wave_alt ProgrammableWaveData_80EB73C, 0, 0, 15, 0	@080EAD98
	voice_programmable_wave_alt ProgrammableWaveData_80EB74C, 0, 0, 15, 0	@080EADA4
	voice_programmable_wave_alt ProgrammableWaveData_80EB75C, 0, 0, 15, 0	@080EADB0
	voice_noise 60, 0, 0, 0, 1, 0, 15, 2	@080EADBC
	voice_square_1 0, 2, 0, 0, 15, 0	@080EADC8
	voice_square_1 0, 2, 0, 0, 15, 0	@080EADD4
	voice_square_1 0, 2, 0, 0, 15, 0	@080EADE0
	voice_square_1 0, 2, 0, 0, 15, 0	@080EADEC
	voice_square_1 0, 2, 0, 0, 15, 0	@080EADF8
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE04
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE10
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE1C
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE28
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE34
	voice_programmable_wave_alt ProgrammableWaveData_80EB72C, 0, 5, 1, 0	@080EAE40
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE4C
	voice_square_1_alt 0, 2, 0, 6, 0, 0	@080EAE58
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE64
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE70
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE7C
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE88
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAE94
	voice_square_1 0, 2, 0, 0, 15, 0	@080EAEA0
	voice_programmable_wave_alt ProgrammableWaveData_80EB72C, 0, 4, 3, 0	@080EAEAC
	voice_square_1_alt 0, 3, 0, 6, 1, 0	@080EAEB8
