	mAlignWord
	@********************** Voicegroup **********************@

	.global voicegroup000
voicegroup000:	@ 0x080E3610
	voice_square_2_alt 0, 0, 0, 15, 0	@080E3610
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@080E361C
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@080E3628
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@080E3634
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@080E3640
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E364C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3658
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3664
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3670
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E367C
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 0	@080E3688
mAlignWord
	voice_square_2_alt 1, 0, 0, 15, 0	@080E3694
mAlignWord
	voice_square_2_alt 2, 0, 0, 15, 0	@080E36A0
mAlignWord
	voice_square_2_alt 3, 0, 0, 15, 0	@080E36AC
mAlignWord
	voice_square_2_alt 2, 2, 0, 15, 0	@080E36B8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E36C4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E36D0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E36DC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E36E8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E36F4
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3700
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E370C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3718
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3724
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3730
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E373C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3748
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3754
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3760
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E376C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3778
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3784
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E3790
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E379C
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E37A8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E37B4
mAlignWord
	voice_square_2_alt 1, 1, 0, 15, 0	@080E37C0
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E37CC
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E37D8
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E37E4
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB6EC, 0, 4, 4, 0	@080E37F0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB6FC, 0, 0, 15, 0	@080E37FC
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB70C, 0, 0, 15, 0	@080E3808
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB71C, 0, 0, 15, 0	@080E3814
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB72C, 0, 0, 15, 0	@080E3820
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB73C, 0, 0, 15, 0	@080E382C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB74C, 0, 0, 15, 0	@080E3838
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB75C, 0, 0, 15, 0	@080E3844
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB76C, 0, 3, 0, 2	@080E3850
mAlignWord
	voice_square_1 0, 2, 0, 0, 15, 0	@080E385C
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 0	@080E3868
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@080E3874
mAlignWord
	voice_square_2_alt 2, 0, 3, 0, 0	@080E3880
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB6EC, 0, 0, 15, 0	@080E388C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB76C, 0, 3, 0, 2	@080E3898
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB6EC, 0, 0, 15, 0	@080E38A4
mAlignWord
	voice_square_2_alt 0, 0, 0, 15, 5	@080E38B0
mAlignWord
	voice_noise 60, 0, 0, 0, 1, 0, 15, 0	@080E38BC
mAlignWord
	voice_noise 60, 0, 0, 1, 0, 0, 15, 0	@080E38C8
mAlignWord
	voice_noise 60, 0, 0, 0, 0, 0, 15, 2	@080E38D4
mAlignWord
	voice_square_2_alt 0, 0, 4, 0, 0	@080E38E0
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB76C, 0, 4, 0, 0	@080E38EC
mAlignWord
	voice_square_2_alt 0, 0, 4, 4, 0	@080E38F8
mAlignWord
	voice_square_2_alt 1, 0, 3, 0, 0	@080E3904
mAlignWord
	voice_square_2_alt 1, 0, 2, 0, 0	@080E3910
mAlignWord
	voice_square_2_alt 3, 0, 1, 0, 1	@080E391C
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB72C, 0, 0, 15, 0	@080E3928
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB73C, 0, 0, 15, 0	@080E3934
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB74C, 0, 0, 15, 0	@080E3940
mAlignWord
	voice_programmable_wave_alt ProgrammableWaveData_80EB75C, 0, 0, 15, 0	@080E394C
mAlignWord
