#ifndef GUARD_DATA_ANIMATIONS_H
#define GUARD_DATA_ANIMATIONS_H

#include "core.h"
#include "animation_commands.h"
#include "sprite.h"

/* TODO: Auto-generate this number once animations get autogenerated */
#if !ENABLE_DECOMP_CREDITS
#if (GAME == GAME_SA2)
#define NUM_SPRITE_ANIMATIONS 1133
#elif (GAME == GAME_SA3)
#define NUM_SPRITE_ANIMATIONS 1524
#endif
#else
// For "Decomp Credits"
#if (GAME == GAME_SA2)
#define NUM_SPRITE_ANIMATIONS (1133 + 1)
#elif (GAME == GAME_SA3)
#define NUM_SPRITE_ANIMATIONS 1524
#endif
#endif

extern const ACmd **const gAnimations[NUM_SPRITE_ANIMATIONS];
extern const SpriteOffset *const gSpriteDimensions[NUM_SPRITE_ANIMATIONS];
extern const OamDataShort *const gSpriteOamData[NUM_SPRITE_ANIMATIONS];
extern const u16 gSpritePalettes[][16];

#endif
