#ifndef GUARD_SA3_GAME_PARAMETERS_ENEMIES_H
#define GUARD_SA3_GAME_PARAMETERS_ENEMIES_H

#include "constants/zones.h" // for TIME()

#define YUKIGASEN_COOLDOWN_FAST TIME(0, 1)
#define YUKIGASEN_COOLDOWN_SLOW TIME(0, 2)

#endif // GUARD_SA3_GAME_PARAMETERS_ENEMIES_H