#ifndef GUARD_SA3_GAME_PARAMETERS_ENEMIES_H
#define GUARD_SA3_GAME_PARAMETERS_ENEMIES_H

#include "constants/zones.h" // for ZONE_TIME_TO_INT()

#define YUKIGASEN_COOLDOWN_FAST ZONE_TIME_TO_INT(0, 1)
#define YUKIGASEN_COOLDOWN_SLOW ZONE_TIME_TO_INT(0, 2)

#endif // GUARD_SA3_GAME_PARAMETERS_ENEMIES_H