#ifndef GUARD_SA3_GAME_PARAMETERS_INTERACTABLES_H
#define GUARD_SA3_GAME_PARAMETERS_INTERACTABLES_H

#define IA_PANDA_CART_START_SPEED (3.00)
#define IA_ROCKET_SPEED           (39.0)

#endif // GUARD_SA3_GAME_PARAMETERS_INTERACTABLES_H